### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by mlitvin** [milosgajdos83/tenus#10]
I want to use [Sourcegraph](https://sourcegraph.com) for tenus code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/milosgajdos83/tenus. (It should only take 30 seconds.)

Thank you!

**Comment by milosgajdos83** [comment]
Done :+1:

**Comment by mlitvin** [comment]
Thanks!
