### ISSUE TITLE
What happened to the master branch?

### ISSUE THREAD

**Issue by mlitvin** [milosgajdos83/tenus#11]
It seems to be overwritten by something completely different? Where all previous history lost

**Comment by GeertJohan** [comment]
Oops. It looks like @milosgajdos83 pushed taurus (https://github.com/milosgajdos83/taurus) to this repo..

**Comment by milosgajdos83** [comment]
WOW. This is weird. I need to figure out what has actually happened here. I have bot ```taurus``` and ```tenus``` repos histories in separate repos on my HW with properly set remotes.

Sorry about this!
