### ISSUE TITLE
Sniffing network traffic

### ISSUE THREAD

**Issue by clintberry** [milosgajdos83/tenus#16]
Could this be used to sniff network traffic? I am trying to create a utility that watches SIP (voip) network traffic and greps it. An easier version of ngrep. Thought it would be cool to do it in go if possible.

**Comment by milosgajdos83** [comment]
I think it might be possible. My best guess would be to use some `pcap` library. Something like [gopacket](https://github.com/google/gopacket) or [gopcap](https://github.com/akrennmair/gopcap).
