### ISSUE TITLE
Is it Possible to add ipTables rules programmatically (without exec :) ) ?

### ISSUE THREAD

**Issue by tigranbs** [milosgajdos83/tenus#9]
Hi
I'm now writing some low level application with Netfilter interaction, and some part of it written in GO <br/>
Is it possible to add/remove some ipTables rules using your library ?<br/>
Without using <code>iptables</code> command line tool !
<br/>
Thanks.

**Comment by milosgajdos83** [comment]
Hi! Sorry for late reply! I've been rather busy lately :-(

Unfortunately this is not possible using this package.

I have been exploring some options in past, but there does not seem to be an easy OS-native way of doing this at the moment. ```Docker``` have taken the ```os.exec``` approach in their iptables [package](https://github.com/docker/libnetwork/tree/master/iptables).

 I'd prefer to do something which would use [libnfnetlink](http://www.netfilter.org/projects/libnfnetlink/index.html) , but unfortunately haven't had time to dedicate much effort to exploring it.

Another possibility could be Erik Hollensbe's dig at this issue in his [iptables](https://github.com/erikh/iptables-iptc) package which uses ```xtables``` library.

**Comment by milosgajdos83** [comment]
Closing this as I've answered the question above :-)
